#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# path
path=('/home/ke/Dropbox/bin' $path)
path=('/home/ke/.local/bin' $path)
export PATH

if [[ -f "${ZDOTDIR:-$HOME}/.zshenv_local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshenv_local"
fi
