#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# z
source $HOME/git/z/z.sh

# pipe into clipboard
alias cb='xclip -selection clipboard'

# open multiple files in tabs
alias vim='vim -p'

# search for ACL bibliography entries in bibtex format
bsb() {
	bibsearch search "$@" -b
}

# arrow keys browse *local* history
# https://superuser.com/questions/446594/separate-up-arrow-lookback-for-local-and-global-zsh-history
bindkey "${terminfo[kcuu1]}" up-line-or-local-history
bindkey "${terminfo[kcud1]}" down-line-or-local-history
up-line-or-local-history() {
    zle set-local-history 1
    zle up-line-or-history
    zle set-local-history 0
}
zle -N up-line-or-local-history
down-line-or-local-history() {
    zle set-local-history 1
    zle down-line-or-history
    zle set-local-history 0
}
zle -N down-line-or-local-history

# show full time
alias ls="${aliases[ls]:-ls} --time-style=full-iso"

# virtualenvwrapper
# Assumes virtualenv, virtualenvwrapper have been installed with:
#     pip3 install --user virtualenv virtualenvwrapper
# Do not use Ubuntu 18.04's virtualenv package, it seems to be broken with
# Python 3.
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/git
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
source $HOME/.local/bin/virtualenvwrapper.sh

# reset terminal to start state (deactive virtualenv and go to home directory)
workoff() {
  deactivate
  cd
}
